import express from 'express';
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import { WebSocketServer } from 'ws';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DB_PATH = path.join(__dirname, 'db.json');
const PORT = process.env.PORT || 4680;

const STATUSES = ['backlog', 'todo', 'doing', 'review', 'done'];

function now() { return new Date().toISOString(); }
function id(prefix = 'id') { return `${prefix}_${Math.random().toString(36).slice(2, 10)}`; }

function seed() {
  const t = now();
  return {
    tasks: [
      { id: id('task'), title: 'Define MVP architecture', description: 'Set stack + deployment path', status: 'doing', priority: 5, assigneeId: null, createdAt: t, updatedAt: t, labels: ['mvp'], autoPick: true },
      { id: id('task'), title: 'Design drag-drop board UX', description: 'Smooth and minimal interactions', status: 'todo', priority: 4, assigneeId: null, createdAt: t, updatedAt: t, labels: ['frontend'], autoPick: true },
      { id: id('task'), title: 'Audit trail schema', description: 'Every state change traceable', status: 'backlog', priority: 4, assigneeId: null, createdAt: t, updatedAt: t, labels: ['backend'], autoPick: true }
    ],
    agents: [
      { id: id('agent'), name: 'Bubba', role: 'AI Principal Engineer', type: 'ai', active: true, capacity: 2, wip: 0, lastHeartbeat: t },
      { id: id('agent'), name: 'Builder-1', role: 'AI Implementer', type: 'ai', active: true, capacity: 2, wip: 0, lastHeartbeat: t },
      { id: id('agent'), name: 'QA-Sentinel', role: 'AI QA', type: 'ai', active: true, capacity: 1, wip: 0, lastHeartbeat: t }
    ],
    audit: [
      { id: id('audit'), at: t, actor: 'system', action: 'seed', entityType: 'workspace', entityId: 'default', summary: 'Initialized TeamFlow workspace' }
    ]
  };
}

function loadDb() {
  if (!fs.existsSync(DB_PATH)) {
    const s = seed();
    fs.writeFileSync(DB_PATH, JSON.stringify(s, null, 2));
    return s;
  }
  return JSON.parse(fs.readFileSync(DB_PATH, 'utf8'));
}

let db = loadDb();

function persist() {
  fs.writeFileSync(DB_PATH, JSON.stringify(db, null, 2));
}

function log(action, entityType, entityId, summary, actor = 'system', meta = {}) {
  db.audit.unshift({ id: id('audit'), at: now(), actor, action, entityType, entityId, summary, meta });
  db.audit = db.audit.slice(0, 500);
}

function taskById(taskId) { return db.tasks.find(t => t.id === taskId); }
function agentById(agentId) { return db.agents.find(a => a.id === agentId); }

function recomputeWip() {
  for (const a of db.agents) a.wip = 0;
  for (const t of db.tasks) {
    if (t.assigneeId && ['doing', 'review'].includes(t.status)) {
      const a = agentById(t.assigneeId);
      if (a) a.wip += 1;
    }
  }
}

function pickTaskForAgent(agent) {
  const candidates = db.tasks
    .filter(t => ['backlog', 'todo'].includes(t.status) && !t.assigneeId && t.autoPick)
    .sort((a, b) => b.priority - a.priority || a.createdAt.localeCompare(b.createdAt));
  return candidates[0];
}

function agentLoop() {
  const t = now();
  const aiAgents = db.agents.filter(a => a.active && a.type === 'ai');
  recomputeWip();

  for (const agent of aiAgents) {
    agent.lastHeartbeat = t;
    while (agent.wip < agent.capacity) {
      const task = pickTaskForAgent(agent);
      if (!task) break;
      task.assigneeId = agent.id;
      task.status = 'doing';
      task.updatedAt = t;
      agent.wip += 1;
      log('autopick', 'task', task.id, `${agent.name} picked up task: ${task.title}`, agent.name);
    }
  }

  for (const task of db.tasks) {
    if (!task.assigneeId) continue;
    const agent = agentById(task.assigneeId);
    if (!agent?.active) continue;

    if (task.status === 'doing' && Math.random() < 0.28) {
      task.status = 'review';
      task.updatedAt = t;
      log('status_change', 'task', task.id, `${agent.name} moved task to review`, agent.name);
    } else if (task.status === 'review' && Math.random() < 0.33) {
      task.status = 'done';
      task.updatedAt = t;
      log('status_change', 'task', task.id, `${agent.name} completed task`, agent.name);
    }
  }

  if (Math.random() < 0.18) {
    const exploratory = {
      id: id('task'),
      title: `Explore improvement: ${['perf', 'UX polish', 'data retention', 'agent coordination'][Math.floor(Math.random()*4)]}`,
      description: 'Agent-discovered opportunity to improve delivery system.',
      status: 'backlog',
      priority: 2 + Math.floor(Math.random() * 3),
      assigneeId: null,
      createdAt: t,
      updatedAt: t,
      labels: ['autogenerated'],
      autoPick: true
    };
    db.tasks.push(exploratory);
    log('create', 'task', exploratory.id, `Agent created exploratory task: ${exploratory.title}`, 'system');
  }

  recomputeWip();
  persist();
  broadcastState();
}

setInterval(agentLoop, 5000);

const app = express();
const server = http.createServer(app);
const wss = new WebSocketServer({ server });

function broadcastState() {
  const payload = JSON.stringify({ type: 'state', data: { tasks: db.tasks, agents: db.agents, audit: db.audit.slice(0, 120), statuses: STATUSES } });
  for (const client of wss.clients) {
    if (client.readyState === 1) client.send(payload);
  }
}

app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

app.get('/api/state', (_req, res) => {
  res.json({ tasks: db.tasks, agents: db.agents, audit: db.audit.slice(0, 120), statuses: STATUSES });
});

app.get('/api/export', (_req, res) => {
  res.json({ exportedAt: now(), tasks: db.tasks });
});

app.post('/api/import', (req, res) => {
  const incoming = Array.isArray(req.body?.tasks) ? req.body.tasks : [];
  let created = 0, updated = 0;
  const t = now();

  for (const it of incoming) {
    if (!it || !it.id) continue;
    const existing = db.tasks.find(x => x.id === it.id);
    if (existing) {
      Object.assign(existing, {
        title: String(it.title ?? existing.title),
        description: String(it.description ?? existing.description ?? ''),
        status: STATUSES.includes(it.status) ? it.status : existing.status,
        priority: Number(it.priority ?? existing.priority ?? 3),
        assigneeId: it.assigneeId ?? existing.assigneeId ?? null,
        labels: Array.isArray(it.labels) ? it.labels : existing.labels ?? [],
        autoPick: it.autoPick ?? existing.autoPick ?? true,
        updatedAt: t
      });
      updated++;
      log('import_update', 'task', existing.id, `Imported update for task: ${existing.title}`, req.body.actor || 'user');
    } else {
      db.tasks.push({
        id: String(it.id),
        title: String(it.title || 'Imported task'),
        description: String(it.description || ''),
        status: STATUSES.includes(it.status) ? it.status : 'backlog',
        priority: Number(it.priority || 3),
        assigneeId: it.assigneeId || null,
        labels: Array.isArray(it.labels) ? it.labels : [],
        autoPick: it.autoPick !== false,
        createdAt: it.createdAt || t,
        updatedAt: t
      });
      created++;
      log('import_create', 'task', it.id, `Imported new task: ${it.title || 'Imported task'}`, req.body.actor || 'user');
    }
  }

  recomputeWip();
  persist();
  broadcastState();
  res.json({ ok: true, created, updated, total: incoming.length });
});

app.get('/api/tasks/:id/history', (req, res) => {
  const rows = db.audit.filter(a => a.entityType === 'task' && a.entityId === req.params.id).slice(0, 120);
  res.json(rows);
});

app.post('/api/tasks', (req, res) => {
  const t = now();
  const task = {
    id: id('task'),
    title: (req.body.title || 'Untitled task').toString(),
    description: (req.body.description || '').toString(),
    status: STATUSES.includes(req.body.status) ? req.body.status : 'backlog',
    priority: Number(req.body.priority || 3),
    assigneeId: req.body.assigneeId || null,
    createdAt: t,
    updatedAt: t,
    labels: Array.isArray(req.body.labels) ? req.body.labels : [],
    autoPick: req.body.autoPick !== false
  };
  db.tasks.push(task);
  log('create', 'task', task.id, `Task created: ${task.title}`, req.body.actor || 'user');
  persist();
  broadcastState();
  res.json(task);
});

app.patch('/api/tasks/:id', (req, res) => {
  const task = taskById(req.params.id);
  if (!task) return res.status(404).json({ error: 'not found' });

  const before = { ...task };
  if (req.body.title !== undefined) task.title = String(req.body.title);
  if (req.body.description !== undefined) task.description = String(req.body.description);
  if (req.body.status !== undefined && STATUSES.includes(req.body.status)) task.status = req.body.status;
  if (req.body.priority !== undefined) task.priority = Number(req.body.priority);
  if (req.body.assigneeId !== undefined) task.assigneeId = req.body.assigneeId || null;
  if (req.body.autoPick !== undefined) task.autoPick = Boolean(req.body.autoPick);
  if (req.body.labels !== undefined) task.labels = Array.isArray(req.body.labels) ? req.body.labels : [];

  task.updatedAt = now();
  log('update', 'task', task.id, `Task updated (${before.status} → ${task.status})`, req.body.actor || 'user', { before, after: task });
  recomputeWip();
  persist();
  broadcastState();
  res.json(task);
});

app.delete('/api/tasks/:id', (req, res) => {
  const idx = db.tasks.findIndex(t => t.id === req.params.id);
  if (idx === -1) return res.status(404).json({ error: 'not found' });
  const [deleted] = db.tasks.splice(idx, 1);
  log('delete', 'task', deleted.id, `Task deleted: ${deleted.title}`, req.body?.actor || 'user');
  recomputeWip();
  persist();
  broadcastState();
  res.json({ ok: true });
});

app.post('/api/agents', (req, res) => {
  const a = {
    id: id('agent'),
    name: String(req.body.name || 'New Agent'),
    role: String(req.body.role || 'Contributor'),
    type: req.body.type === 'human' ? 'human' : 'ai',
    active: req.body.active !== false,
    capacity: Number(req.body.capacity || 2),
    wip: 0,
    lastHeartbeat: now()
  };
  db.agents.push(a);
  log('create', 'agent', a.id, `Agent created: ${a.name}`, req.body.actor || 'user');
  persist();
  broadcastState();
  res.json(a);
});

app.patch('/api/agents/:id', (req, res) => {
  const a = agentById(req.params.id);
  if (!a) return res.status(404).json({ error: 'not found' });
  if (req.body.name !== undefined) a.name = String(req.body.name);
  if (req.body.role !== undefined) a.role = String(req.body.role);
  if (req.body.active !== undefined) a.active = Boolean(req.body.active);
  if (req.body.capacity !== undefined) a.capacity = Number(req.body.capacity);
  log('update', 'agent', a.id, `Agent updated: ${a.name}`, req.body.actor || 'user');
  persist();
  broadcastState();
  res.json(a);
});

app.get('/health', (_req, res) => res.json({ ok: true, at: now() }));

wss.on('connection', (ws) => {
  ws.send(JSON.stringify({ type: 'state', data: { tasks: db.tasks, agents: db.agents, audit: db.audit.slice(0, 120), statuses: STATUSES } }));
});

server.listen(PORT, '0.0.0.0', () => {
  console.log(`TeamFlow Kanban running on http://0.0.0.0:${PORT}`);
});
